version: "3.9"

services:
  backend:
    image: your_user/coffeeshop-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: coffeeshop-backend
    ports:
      - "8089:8089"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/coffeeshop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
    depends_on:
      - mysql
    networks:
      - coffeeshop-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: coffeeshop-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - coffeeshop-network

  mysql:
    image: mysql:8.0
    container_name: coffeeshop-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=coffeeshop
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - coffeeshop-network

networks:
  coffeeshop-network:

volumes:
  mysql_data:
